version: 0.2

env:
  variables:
     packageS3: 's3://sijiehanbucket'
     ecruri: '898111891143.dkr.ecr.cn-north-1.amazonaws.com.cn/helloworld'
     projectName: 'helloworld'
     gitRepoName: 'masterbuilderecs'
     currentdate: 'null'

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install xml-twig-tools -y
  pre_build:
    commands:
      - mvn clean package -Pdeploy -Dmaven.test.skip
      - /usr/bin/xml_grep "/project/version" pom.xml --text_only > /tmp/version.txt
      - mv target/*.jar target/$projectName-"$(cat /tmp/version.txt)"-"master.jar"
      - sed -i 's/versionbereplaced/'"$(cat /tmp/version.txt)"'/g' Dockerfile
      - aws s3 cp target/$projectName-"$(cat /tmp/version.txt)"-"master.jar" $packageS3/${gitRepoName}/${currentdate}/ --region cn-north-1
      - aws s3 cp ./ $packageS3/${gitRepoName}/${currentdate}/ --region cn-north-1 --recursive --exclude 'src/*' --exclude '.git/*' --exclude 'target/*'
  build:
    commands:
      - cd /tmp/
      - aws s3 cp $packageS3/${gitRepoName}/${currentdate}/ ./ --region cn-north-1 --recursive
      - docker build -t ${projectName} .
  post_build:
    commands:
      - $(aws ecr get-login --region cn-north-1 --no-include-email)
      - docker tag ${projectName}:latest ${ecruri}:"$(cat /tmp/version.txt)"-${currentdate}
      - docker push ${ecruri}:"$(cat /tmp/version.txt)"-${currentdate}
      - echo "$(cat /tmp/version.txt)"-${currentdate}#${packageS3}/${gitRepoName}/${currentdate} > /tmp/latest_image
      - aws s3 cp /tmp/latest_image ${packageS3}/${gitRepoName}/ --region cn-north-1
#artifacts:
  #files:
